### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by qwertychouskie**

### CODE REVIEW

**Comment by MTres19** [comment]
I will try to stay patient but will also be blunt in saying that I do not consider this type of thing a contribution. This is not a bugfix---you probably just ran it through a spelling-and-grammar-checker. Nor is it a true addition---you didn't put any effort any new content. In short, it is nothing more then a list of trivial complaints disguised as a pull request, and it's not worth the effort it would take to merge these with work I haven't yet pushed to GitHub.

The STK team has been patient with your bug reports, but I don't feel obligated to deal with that type of complaints in my own repository. Most likely most open-source projects won't either. I explicitly told you that fixing grammar issues were probably not a priority and that you could help by writing the Communication page. That doesn't take any programming skills. All it takes is a real desire to help out.

Essentially, you want to receive credit for complaining, and anyone can do _that_. That's why I'm closing this PR.

Regards,

**Comment by MTres19** [comment]
I will, however, open a issue to remind myself to run things through a spelling-checker.

**Comment by qwertychouskie** [comment]
Sorry, wasn't trying to complain.  I didn't realize merging was more complicated than clicking the merge button, I never would have created this PR if I had known. :(

**Comment by MTres19** [comment]
Merging is not particularly difficult besides doing a git pull on my end. But the main problem is that this is not really a contribution. You seem to want to help, but when I suggested an option which required reasonable effort (i.e. working on the Communication page) you never responded. That is the problem: you want to help, but are unwilling to actually spend the time needed to do so. And complaining about trivial problems while being unwilling to help with the bigger issues only wastes team members' time. This is pretty much what Auria already reminded you of [here](https://github.com/supertuxkart/stk-code/issues/2527).

I closed the PR because I want you to help with more important things, not because I can't merge it.

Regards,

—

**Pull request closed without merging**
